[package]
name = "nash"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
whoami = "1.5.2"
rustyline = "9.1.2"
rustyline-derive = "0.7.0"
dirs = "4.0.0"
git2 = "0.19.0"
reqwest = { version = "0.12.8", features = ["json"] }
