name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build nash_build_mgr project
      run: |
        cd ./nash_build_mgr
        cargo build --release
        cd ..
    - name: Test
      run: |
            nash_build_mgr/target/release
